#============================================================================
# DATABASE
#============================================================================
db:
  name : account
  host : localhost
  port : 4041
  username : postgres
  password : postgres
  auto-reconnect : true
  ssl : false

#============================================================================
# REDIS
#============================================================================
redis:
  host: localhost
  port: 4040

#============================================================================
# LOGGING
#============================================================================
log:
  enabled: false
  file:
    path : /home/ayubi/sjp/java/LOGGER/account-service.log

#============================================================================
# REST-CLIENT
#============================================================================
rest:
  otp:
    base-path: http://localhost:6868/otp-api/v1