#============================================================================
# SERVER
#============================================================================
server:
  port: 8567
  tomcat:
    max-threads: 4000
    connection-timeout: 30000 #in milisecond
  servlet:
    context-path: /sjp-movie-api
#============================================================================
# SPRING
#============================================================================
spring:
  boot:
    admin:
      client:
        url: http://localhost:8567 # SBA Config , disable if unused
  #  profiles :
  #    active : local
  application:
    name: sjp-movie-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${db.host}:${db.port}/${db.name}
    username: ${db.username}
    password: ${db.password}
    hikari:
      minimumIdle: 10
      maximumPoolSize: 60
      idleTimeout: 30000
      poolName: search-item-cp
      maxLifetime: 2000000
      connectionTimeout: 60000
  jpa:
    show-sql: true
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        naming_strategy: org.hibernate.cfg.EJB3NamingStrategy
        dialect: org.hibernate.dialect.PostgreSQL9Dialect
        ddl-auto: validate     # Hibernate ddl auto (create, create-drop, validate, update)
  banner:
    location: banner.txt
  flyway:
    enabled: true # set this value to true when you want to run in local container

#============================================================================
# DATABASE
#============================================================================
db:
  name: movie_api
  host: localhost
  port: 5432
  username: postgres
  password: postgres
  auto-reconnect: true
  ssl: false

#============================================================================
# LOGGER
#============================================================================
logging:
  config: classpath:logback-spring.xml
  file: ${log.file.path}
  level:
    id.sjp.movie.api: DEBUG
  api:
    base-path: ${log.base.path}

#============================================================================
# LOG FILE
#============================================================================
log:
  enabled: false
  file:
    path: /home/ayubi/sjp/log/sjp-movie-api.log
  base:
    path: localhost:8765/sjp-movie-api-logger

#============================================================================
# SWAGGER
#============================================================================
swagger:
  vendor:
    name: SJP Movie API
    value: 1.0.0
  metadata:
    title: SJP Movie API
    description: This is documentation sjp movie api by syahrul ayubi
    version: 1.0.0
    tos: This Documentation is Only Available on Development Phase
    license: Apache License Version 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0
    contact:
      name: Syahrul Ayubi
      url: https://www.facebook.com/syahrul.ayubii/
      email: syahrul.ayubi@gmail.com
#============================================================================
# ACTUATOR
#============================================================================
management:
  endpoint:
    health:
      show-details: never
  endpoints:
    web:
      base-path: /
      exposure:
        include: "*"
#============================================================================
# INFO
#============================================================================
info:
  app:
    encoding: "@project.build.sourceEncoding@"
    java:
      version: "@java.version@"